name: Publish .NET and Upload Artifacts

inputs:
  project-path: 
    required: true
  webapp-artifact-name: 
    required: true
    default: webapp
  infrastructure-artifact-name: 
    required: true
    default: infrastructure

runs:
  using: composite
  steps:
  - name: Publish
    run: dotnet publish ${{ inputs.project-path }} --configuration Release --output ${{ inputs.webapp-artifact-name }}
  - name: Upload a build artifact
    uses: actions/upload-artifact@v3
    with:
      name: ${{ inputs.webapp-artifact-name }}
      path: ${{ inputs.webapp-artifact-name }}/**
      if-no-files-found: error
  - name: Upload an ARM template artifact
    uses: actions/upload-artifact@v3
    with:
      name: ${{ inputs.infrastructure-artifact-name }}
      path: ${{ inputs.infrastructure-artifact-name }}/**
      if-no-files-found: error
