name: Deploy Bicep and Azure Web App

inputs:
  app-name:
    required: true
  resource-group-name:
    required: true
  azure-credentials:
    required: true
  azure-subscription:
    required: true
  template-path:
    required: true
  parameters-path:
    required: true
  publish-profile:
    required: true
  webapp-artifact-name: 
    required: false
    default: webapp
  infrastructure-artifact-name: 
    required: false
    default: infrastructure

runs:
  using: composite
  steps:
  - name: Download a build artifact
    uses: actions/download-artifact@v3
    with:
      name: ${{ inputs.webapp-artifact-name }}
      path: ${{ inputs.webapp-artifact-name }}
  - name: Download an ARM template artifact
    uses: actions/download-artifact@v3
    with:
      name: ${{ inputs.infrastructure-artifact-name }}
      path: ${{ inputs.infrastructure-artifact-name }}
  - name: Login via Azure CLI
    uses: azure/login@v1
    with:
      creds: ${{ inputs.azure-credentials }}
  - name: Deploy ARM template
    uses: azure/arm-deploy@v1
    with:
      subscriptionId: ${{ inputs.azure-subscription }}
      resourceGroupName: ${{ inputs.resource-group-name }}
      template: ${{ inputs.template-path }}
      parameters: ${{ inputs.parameters-path }}
      failOnStdErr: false
  - name: Deploy Azure web app
  - uses: azure/webapps-deploy@v2
    with:
      app-name: ${{ inputs.app-name }}
      package: ${{ inputs.webapp-artifact-name }}
      publish-profile: ${{ inputs.publish-profile }}
  - name: Logout via Azure CLI
    run: az logout
