name: Build and Test .NET

runs:
  using: composite
  steps:
  - name: Setup .NET
    uses: actions/setup-dotnet@v3
  - name: Restore dependencies
    run: dotnet restore ./
  - name: Build
    run: dotnet build --no-restore --configuration Release ./
  - name: Test
    run: dotnet test --no-build --configuration Release --verbosity normal ./
