name: Build

on:
  pull_request:
    branches:
      - main

  workflow_call:
    inputs:
      project-path:
        type: string
        required: true

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Publish
        if: ${{ github.event_name == 'workflow_call' }}
        run: dotnet publish --no-build ${{ inputs.project-path }} --configuration Release --output webapp

      - name: Upload a build artifact
        if: ${{ github.event_name == 'workflow_call' }}
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: webapp/**
          if-no-files-found: error

      - name: Upload an ARM template artifact
        if: ${{ github.event_name == 'workflow_call' }}
        uses: actions/upload-artifact@v4
        with:
          name: infra
          path: infra/azure/**
          if-no-files-found: error
