name: CI

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out a repo
      uses: actions/checkout@v3
    - name: Build and test .NET
      uses: ./.github/actions/build-and-test-dotnet
