name: CI/CD

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out a repo
      uses: actions/checkout@v3
    - name: Build and test .NET
      uses: ./.github/actions/build-and-test-dotnet
    - name: Publish .NET app and upload artifact
      uses: ./.github/actions/publish-and-upload-artifacts
      with:
        project-path: src/WeightTracker.Web/WeightTracker.Web.csproj
  
  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy bicep and web app to dev
        uses: ./.github/actions/deploy-bicep-and-az-webapp
        with:
          app-name: ${{ env.APP_NAME }}
          resource-group-name: ${{ env.RESOURCE_GROUP_NAME }}
          azure-credentials: ${{ env.AZURE_CREDENTIALS }}
          azure-subscription: ${{ vars.AZURE_SUBSCRIPTION }}
          template-path: bicep/main.bicep
          parameters-path: bicep/parameters.dev.json
          publish-profile: ${{ env.PUBLISH_PROFILE }}

  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy bicep and web app to prod
        uses: ./.github/actions/deploy-bicep-and-az-webapp
        with:
          app-name: ${{ env.APP_NAME }}
          resource-group-name: ${{ env.RESOURCE_GROUP_NAME }}
          azure-credentials: ${{ env.AZURE_CREDENTIALS }}
          azure-subscription: ${{ vars.AZURE_SUBSCRIPTION }}
          template-path: bicep/main.bicep
          parameters-path: bicep/parameters.prod.json
          publish-profile: ${{ env.PUBLISH_PROFILE }}
