name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

      arm-path:
        type: string
        required: true

      arm-parameters-path:
        type: string
        required: true

      infra-artifact-name:
        type: string
        required: false
        default: infra

      webapp-artifact-name:
        type: string
        required: false
        default: webapp

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download an infra artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.infra-artifact-name }}
          path: ${{ inputs.infra-artifact-name }}

      - name: Download a web app artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.webapp-artifact-name }}
          path: ${{ inputs.webapp-artifact-name }}

      - name: Deploy ARM template
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          template: ${{ inputs.arm-path }}
          parameters: ${{ inputs.arm-parameters-path }}
          failOnStdErr: false

      - name: Deploy Azure web app
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.APP_NAME }}
          package: ${{ inputs.webapp-artifact-name }}

      - name: Logout via Azure CLI
        run: az logout
