name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      arm-path:
        type: string
        required: true
      arm-parameters-path:
        type: string
        required: true
      artifact-name:
        type: string
        required: false
        default: webapp

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download a build artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-name }}
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy ARM template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          template: ${{ inputs.arm-path }}
          parameters: ${{ inputs.arm-parameters-path }}
          failOnStdErr: false
      - name: Deploy Azure web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.APP_NAME }}
          package: ${{ inputs.artifact-name }}
      - name: Logout via Azure CLI
        run: az logout
