name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      template-path:
        type: string
        required: true
      parameters-path:
        type: string
        required: true
      webapp-artifact-name:
        type: string
        required: false
        default: webapp
      infrastructure-artifact-name:
        type: string
        required: false
        default: infrastructure

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Download a build artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.webapp-artifact-name }}
          path: ${{ inputs.webapp-artifact-name }}
      - name: Download an ARM template artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.infrastructure-artifact-name }}
          path: ${{ inputs.infrastructure-artifact-name }}
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}
      - name: Deploy ARM template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ${{ inputs.template-path }}
          parameters: ${{ inputs.parameters-path }}
          failOnStdErr: false
      - name: Deploy Azure web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          package: ${{ inputs.webapp-artifact-name }}
          publish-profile: ${{ env.PUBLISH_PROFILE }}
      - name: Logout via Azure CLI
        run: az logout
