name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      arm-path:
        type: string
        required: true
      arm-parameters-path:
        type: string
        required: true
      webapp-artifact-name:
        type: string
        required: false
        default: webapp
      infrastructure-artifact-name:
        type: string
        required: false
        default: infra

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Download a build artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.webapp-artifact-name }}
          path: ${{ inputs.webapp-artifact-name }}
      - name: Download an ARM template artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.infrastructure-artifact-name }}
          path: ${{ inputs.infrastructure-artifact-name }}
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy ARM template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          template: ${{ inputs.arm-path }}
          parameters: ${{ inputs.arm-parameters-path }}
          failOnStdErr: false
      - name: Deploy Azure web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.APP_NAME }}
          package: ${{ inputs.webapp-artifact-name }}
          publish-profile: ${{ vars.PUBLISH_PROFILE }}
      - name: Logout via Azure CLI
        run: az logout
