name: CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      project-path: src/api/WeightTracker.Api/WeightTracker.Api.csproj

  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    needs: build
    with:
      environment: prod
      arm-path: infrastructure/main.bicep
      arm-parameters-path: infrastructure/parameters.json
